//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Language {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_vi {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_vi() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Project.Language.AppResources.vi", typeof(AppResources_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        internal static string TotalTimeOn {
            get {
                return ResourceManager.GetString("TotalTimeOn", resourceCulture);
            }
        }
        
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        internal static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        internal static string S3WANTitle {
            get {
                return ResourceManager.GetString("S3WANTitle", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string DoingLogin {
            get {
                return ResourceManager.GetString("DoingLogin", resourceCulture);
            }
        }
        
        internal static string LoginOK {
            get {
                return ResourceManager.GetString("LoginOK", resourceCulture);
            }
        }
        
        internal static string LoginFailPleaseRecheck {
            get {
                return ResourceManager.GetString("LoginFailPleaseRecheck", resourceCulture);
            }
        }
        
        internal static string PleaseConfigImportantSetting {
            get {
                return ResourceManager.GetString("PleaseConfigImportantSetting", resourceCulture);
            }
        }
        
        internal static string NetworkErrorPleaseRecheck {
            get {
                return ResourceManager.GetString("NetworkErrorPleaseRecheck", resourceCulture);
            }
        }
        
        internal static string UsernameOrPasswordIsWrong {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsWrong", resourceCulture);
            }
        }
        
        internal static string UserIsExpiredPleaseContactAdmin {
            get {
                return ResourceManager.GetString("UserIsExpiredPleaseContactAdmin", resourceCulture);
            }
        }
        
        internal static string UserIsLockedPleaseContactAdmin {
            get {
                return ResourceManager.GetString("UserIsLockedPleaseContactAdmin", resourceCulture);
            }
        }
        
        internal static string Login_OKThenLoadAllData {
            get {
                return ResourceManager.GetString("Login_OKThenLoadAllData", resourceCulture);
            }
        }
        
        internal static string Login_LoadDeviceInfoFail {
            get {
                return ResourceManager.GetString("Login_LoadDeviceInfoFail", resourceCulture);
            }
        }
        
        internal static string Login_LoadUserInfoFail {
            get {
                return ResourceManager.GetString("Login_LoadUserInfoFail", resourceCulture);
            }
        }
        
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        internal static string FindGatewayLineDevice {
            get {
                return ResourceManager.GetString("FindGatewayLineDevice", resourceCulture);
            }
        }
        
        internal static string TotalGateways {
            get {
                return ResourceManager.GetString("TotalGateways", resourceCulture);
            }
        }
        
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        internal static string TotalLines {
            get {
                return ResourceManager.GetString("TotalLines", resourceCulture);
            }
        }
        
        internal static string DetailInformation {
            get {
                return ResourceManager.GetString("DetailInformation", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        internal static string WorkingTime {
            get {
                return ResourceManager.GetString("WorkingTime", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        internal static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        internal static string OnlineFrom {
            get {
                return ResourceManager.GetString("OnlineFrom", resourceCulture);
            }
        }
        
        internal static string OfflineAt {
            get {
                return ResourceManager.GetString("OfflineAt", resourceCulture);
            }
        }
        
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        internal static string NotifyAndError {
            get {
                return ResourceManager.GetString("NotifyAndError", resourceCulture);
            }
        }
        
        internal static string PowerMeter {
            get {
                return ResourceManager.GetString("PowerMeter", resourceCulture);
            }
        }
        
        internal static string OutputScheduler {
            get {
                return ResourceManager.GetString("OutputScheduler", resourceCulture);
            }
        }
        
        internal static string LightAndDeviceScheduler {
            get {
                return ResourceManager.GetString("LightAndDeviceScheduler", resourceCulture);
            }
        }
        
        internal static string CheckingScheduler {
            get {
                return ResourceManager.GetString("CheckingScheduler", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string TotalLights {
            get {
                return ResourceManager.GetString("TotalLights", resourceCulture);
            }
        }
        
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string LineIndex {
            get {
                return ResourceManager.GetString("LineIndex", resourceCulture);
            }
        }
        
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        internal static string TemperatureIsOver {
            get {
                return ResourceManager.GetString("TemperatureIsOver", resourceCulture);
            }
        }
        
        internal static string TemperatureIsGoingNormal {
            get {
                return ResourceManager.GetString("TemperatureIsGoingNormal", resourceCulture);
            }
        }
        
        internal static string CurrentIsOver {
            get {
                return ResourceManager.GetString("CurrentIsOver", resourceCulture);
            }
        }
        
        internal static string CurrentIsGoingNormal {
            get {
                return ResourceManager.GetString("CurrentIsGoingNormal", resourceCulture);
            }
        }
        
        internal static string DeviceOnButNoCurrent {
            get {
                return ResourceManager.GetString("DeviceOnButNoCurrent", resourceCulture);
            }
        }
        
        internal static string DeviceOnIsGoingNormal {
            get {
                return ResourceManager.GetString("DeviceOnIsGoingNormal", resourceCulture);
            }
        }
        
        internal static string DeviceUsingByUnStableInput {
            get {
                return ResourceManager.GetString("DeviceUsingByUnStableInput", resourceCulture);
            }
        }
        
        internal static string DeviceUsingByLowInput {
            get {
                return ResourceManager.GetString("DeviceUsingByLowInput", resourceCulture);
            }
        }
        
        internal static string DeviceUsingByHighInput {
            get {
                return ResourceManager.GetString("DeviceUsingByHighInput", resourceCulture);
            }
        }
        
        internal static string DeviceReturnNormalInput {
            get {
                return ResourceManager.GetString("DeviceReturnNormalInput", resourceCulture);
            }
        }
        
        internal static string DeviceNotResponseWhenCheck {
            get {
                return ResourceManager.GetString("DeviceNotResponseWhenCheck", resourceCulture);
            }
        }
        
        internal static string OutputChannelOnButNoVoltage {
            get {
                return ResourceManager.GetString("OutputChannelOnButNoVoltage", resourceCulture);
            }
        }
        
        internal static string OutputChannelOffButHasVoltage {
            get {
                return ResourceManager.GetString("OutputChannelOffButHasVoltage", resourceCulture);
            }
        }
        
        internal static string OutputChannelIsOK {
            get {
                return ResourceManager.GetString("OutputChannelIsOK", resourceCulture);
            }
        }
        
        internal static string DeviceIsPowerOn {
            get {
                return ResourceManager.GetString("DeviceIsPowerOn", resourceCulture);
            }
        }
        
        internal static string DeviceIsReset {
            get {
                return ResourceManager.GetString("DeviceIsReset", resourceCulture);
            }
        }
        
        internal static string GatewayChannel {
            get {
                return ResourceManager.GetString("GatewayChannel", resourceCulture);
            }
        }
        
        internal static string DeviceHasNoAnyNotificationsOrErrors {
            get {
                return ResourceManager.GetString("DeviceHasNoAnyNotificationsOrErrors", resourceCulture);
            }
        }
        
        internal static string VoltageP1 {
            get {
                return ResourceManager.GetString("VoltageP1", resourceCulture);
            }
        }
        
        internal static string VoltageP2 {
            get {
                return ResourceManager.GetString("VoltageP2", resourceCulture);
            }
        }
        
        internal static string VoltageP3 {
            get {
                return ResourceManager.GetString("VoltageP3", resourceCulture);
            }
        }
        
        internal static string CurrentP1 {
            get {
                return ResourceManager.GetString("CurrentP1", resourceCulture);
            }
        }
        
        internal static string CurrentP2 {
            get {
                return ResourceManager.GetString("CurrentP2", resourceCulture);
            }
        }
        
        internal static string CurrentP3 {
            get {
                return ResourceManager.GetString("CurrentP3", resourceCulture);
            }
        }
        
        internal static string PowerP1 {
            get {
                return ResourceManager.GetString("PowerP1", resourceCulture);
            }
        }
        
        internal static string PowerP2 {
            get {
                return ResourceManager.GetString("PowerP2", resourceCulture);
            }
        }
        
        internal static string PowerP3 {
            get {
                return ResourceManager.GetString("PowerP3", resourceCulture);
            }
        }
        
        internal static string PowerTotal {
            get {
                return ResourceManager.GetString("PowerTotal", resourceCulture);
            }
        }
        
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        internal static string TotalConsumption {
            get {
                return ResourceManager.GetString("TotalConsumption", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string DeviceSetup {
            get {
                return ResourceManager.GetString("DeviceSetup", resourceCulture);
            }
        }
        
        internal static string ChangeNameAndDes {
            get {
                return ResourceManager.GetString("ChangeNameAndDes", resourceCulture);
            }
        }
        
        internal static string ScanDevice {
            get {
                return ResourceManager.GetString("ScanDevice", resourceCulture);
            }
        }
        
        internal static string ControlHistory {
            get {
                return ResourceManager.GetString("ControlHistory", resourceCulture);
            }
        }
        
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        internal static string DeviceDescription {
            get {
                return ResourceManager.GetString("DeviceDescription", resourceCulture);
            }
        }
        
        internal static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        internal static string ChangeDescription {
            get {
                return ResourceManager.GetString("ChangeDescription", resourceCulture);
            }
        }
        
        internal static string DoingUpdateNewName {
            get {
                return ResourceManager.GetString("DoingUpdateNewName", resourceCulture);
            }
        }
        
        internal static string DoingUpdateNewDescription {
            get {
                return ResourceManager.GetString("DoingUpdateNewDescription", resourceCulture);
            }
        }
        
        internal static string SorryYouHaveNoPermissionToDoThisAction {
            get {
                return ResourceManager.GetString("SorryYouHaveNoPermissionToDoThisAction", resourceCulture);
            }
        }
        
        internal static string SorryUnknownError {
            get {
                return ResourceManager.GetString("SorryUnknownError", resourceCulture);
            }
        }
        
        internal static string ScanAndSetup {
            get {
                return ResourceManager.GetString("ScanAndSetup", resourceCulture);
            }
        }
        
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        internal static string TotalDevices {
            get {
                return ResourceManager.GetString("TotalDevices", resourceCulture);
            }
        }
        
        internal static string SetAnotherDevice {
            get {
                return ResourceManager.GetString("SetAnotherDevice", resourceCulture);
            }
        }
        
        internal static string ScanDeviceHint {
            get {
                return ResourceManager.GetString("ScanDeviceHint", resourceCulture);
            }
        }
        
        internal static string DevicePasswordHint {
            get {
                return ResourceManager.GetString("DevicePasswordHint", resourceCulture);
            }
        }
        
        internal static string SetID {
            get {
                return ResourceManager.GetString("SetID", resourceCulture);
            }
        }
        
        internal static string AddNewLightLine {
            get {
                return ResourceManager.GetString("AddNewLightLine", resourceCulture);
            }
        }
        
        internal static string SyncLightLineToGateway {
            get {
                return ResourceManager.GetString("SyncLightLineToGateway", resourceCulture);
            }
        }
        
        internal static string SetupGateway {
            get {
                return ResourceManager.GetString("SetupGateway", resourceCulture);
            }
        }
        
        internal static string SetLocation {
            get {
                return ResourceManager.GetString("SetLocation", resourceCulture);
            }
        }
        
        internal static string AddNewVirtualLine {
            get {
                return ResourceManager.GetString("AddNewVirtualLine", resourceCulture);
            }
        }
        
        internal static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        internal static string DeleteGateway {
            get {
                return ResourceManager.GetString("DeleteGateway", resourceCulture);
            }
        }
        
        internal static string DeleteGwWarning {
            get {
                return ResourceManager.GetString("DeleteGwWarning", resourceCulture);
            }
        }

        internal static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string InputSerial {
            get {
                return ResourceManager.GetString("InputSerial", resourceCulture);
            }
        }
        
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        internal static string InputSerialDescription {
            get {
                return ResourceManager.GetString("InputSerialDescription", resourceCulture);
            }
        }
        
        internal static string GatewayIsNotExistPleaseRecheck {
            get {
                return ResourceManager.GetString("GatewayIsNotExistPleaseRecheck", resourceCulture);
            }
        }
        
        internal static string DoingCheckSerial {
            get {
                return ResourceManager.GetString("DoingCheckSerial", resourceCulture);
            }
        }
        
        internal static string DeviceIsValid {
            get {
                return ResourceManager.GetString("DeviceIsValid", resourceCulture);
            }
        }
        
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        internal static string AddNewGatewayIsOK {
            get {
                return ResourceManager.GetString("AddNewGatewayIsOK", resourceCulture);
            }
        }
        
        internal static string SetName {
            get {
                return ResourceManager.GetString("SetName", resourceCulture);
            }
        }
        
        internal static string SetIndex {
            get {
                return ResourceManager.GetString("SetIndex", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string SetTotalDimerLight {
            get {
                return ResourceManager.GetString("SetTotalDimerLight", resourceCulture);
            }
        }
        
        internal static string SetTotalTimer {
            get {
                return ResourceManager.GetString("SetTotalTimer", resourceCulture);
            }
        }
        
        internal static string TotalTimers {
            get {
                return ResourceManager.GetString("TotalTimers", resourceCulture);
            }
        }
        
        internal static string DoingAddNewLightLine {
            get {
                return ResourceManager.GetString("DoingAddNewLightLine", resourceCulture);
            }
        }
        
        internal static string CreateNewLightLineOK {
            get {
                return ResourceManager.GetString("CreateNewLightLineOK", resourceCulture);
            }
        }
        
        internal static string PleaseSelectAnotherLineIndex {
            get {
                return ResourceManager.GetString("PleaseSelectAnotherLineIndex", resourceCulture);
            }
        }
        
        internal static string LineName {
            get {
                return ResourceManager.GetString("LineName", resourceCulture);
            }
        }
        
        internal static string LineDescription {
            get {
                return ResourceManager.GetString("LineDescription", resourceCulture);
            }
        }
        
        internal static string UpdateDeviceOnLine {
            get {
                return ResourceManager.GetString("UpdateDeviceOnLine", resourceCulture);
            }
        }
        
        internal static string DoingUpdateDeviceOnLine {
            get {
                return ResourceManager.GetString("DoingUpdateDeviceOnLine", resourceCulture);
            }
        }
        
        internal static string UpdateDeviceOnLineOK {
            get {
                return ResourceManager.GetString("UpdateDeviceOnLineOK", resourceCulture);
            }
        }
        
        internal static string SetNewIDOK {
            get {
                return ResourceManager.GetString("SetNewIDOK", resourceCulture);
            }
        }
        
        internal static string SetNewIDFailPleaseRecheck {
            get {
                return ResourceManager.GetString("SetNewIDFailPleaseRecheck", resourceCulture);
            }
        }
        
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        internal static string DeleteDvNotifyWarning {
            get {
                return ResourceManager.GetString("DeleteDvNotifyWarning", resourceCulture);
            }
        }
        
        internal static string DoingDeleteAllNotify {
            get {
                return ResourceManager.GetString("DoingDeleteAllNotify", resourceCulture);
            }
        }
        
        internal static string DeleteAllNotifyOK {
            get {
                return ResourceManager.GetString("DeleteAllNotifyOK", resourceCulture);
            }
        }
        
        internal static string DeleteAllNotifyFail {
            get {
                return ResourceManager.GetString("DeleteAllNotifyFail", resourceCulture);
            }
        }
        
        internal static string TotalLineLightIsOver100 {
            get {
                return ResourceManager.GetString("TotalLineLightIsOver100", resourceCulture);
            }
        }
        
        internal static string CanNotConnectToCloud {
            get {
                return ResourceManager.GetString("CanNotConnectToCloud", resourceCulture);
            }
        }
        
        internal static string CanNotSyncToGateway {
            get {
                return ResourceManager.GetString("CanNotSyncToGateway", resourceCulture);
            }
        }
        
        internal static string SyncLightLineToGatewayOK {
            get {
                return ResourceManager.GetString("SyncLightLineToGatewayOK", resourceCulture);
            }
        }
        
        internal static string DoingSyncLightLine {
            get {
                return ResourceManager.GetString("DoingSyncLightLine", resourceCulture);
            }
        }
        
        internal static string BiggerThan0AndSmaller {
            get {
                return ResourceManager.GetString("BiggerThan0AndSmaller", resourceCulture);
            }
        }
        
        internal static string InvalidValuePleaseRecheck {
            get {
                return ResourceManager.GetString("InvalidValuePleaseRecheck", resourceCulture);
            }
        }
        
        internal static string DoingAddNewVirtualLine {
            get {
                return ResourceManager.GetString("DoingAddNewVirtualLine", resourceCulture);
            }
        }
        
        internal static string AddNewVirtualLineOK {
            get {
                return ResourceManager.GetString("AddNewVirtualLineOK", resourceCulture);
            }
        }
        
        internal static string AddNewVirtualLineFail {
            get {
                return ResourceManager.GetString("AddNewVirtualLineFail", resourceCulture);
            }
        }
        
        internal static string VirtualLineIsExistSelectAnotherIndex {
            get {
                return ResourceManager.GetString("VirtualLineIsExistSelectAnotherIndex", resourceCulture);
            }
        }
        
        internal static string VirtualLine {
            get {
                return ResourceManager.GetString("VirtualLine", resourceCulture);
            }
        }
        
        internal static string From0To {
            get {
                return ResourceManager.GetString("From0To", resourceCulture);
            }
        }
        
        internal static string From1To {
            get {
                return ResourceManager.GetString("From1To", resourceCulture);
            }
        }
        
        internal static string DeleteLine {
            get {
                return ResourceManager.GetString("DeleteLine", resourceCulture);
            }
        }
        
        internal static string DeleteLineOK {
            get {
                return ResourceManager.GetString("DeleteLineOK", resourceCulture);
            }
        }
        
        internal static string SetAnotherDeviceHint {
            get {
                return ResourceManager.GetString("SetAnotherDeviceHint", resourceCulture);
            }
        }
        
        internal static string UpdateNewNameOK {
            get {
                return ResourceManager.GetString("UpdateNewNameOK", resourceCulture);
            }
        }
        
        internal static string UpdateDescriptionOK {
            get {
                return ResourceManager.GetString("UpdateDescriptionOK", resourceCulture);
            }
        }
        
        internal static string TotalScripts {
            get {
                return ResourceManager.GetString("TotalScripts", resourceCulture);
            }
        }
        
        internal static string LoadingScriptsData {
            get {
                return ResourceManager.GetString("LoadingScriptsData", resourceCulture);
            }
        }
        
        internal static string IsActivate {
            get {
                return ResourceManager.GetString("IsActivate", resourceCulture);
            }
        }
        
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        internal static string NotActivate {
            get {
                return ResourceManager.GetString("NotActivate", resourceCulture);
            }
        }
        
        internal static string CreateNewScript {
            get {
                return ResourceManager.GetString("CreateNewScript", resourceCulture);
            }
        }
        
        internal static string CreateNewScriptOK {
            get {
                return ResourceManager.GetString("CreateNewScriptOK", resourceCulture);
            }
        }
        
        internal static string DeleteScript {
            get {
                return ResourceManager.GetString("DeleteScript", resourceCulture);
            }
        }
        
        internal static string DeleteScriptWarning {
            get {
                return ResourceManager.GetString("DeleteScriptWarning", resourceCulture);
            }
        }
        
        internal static string ScriptIsNotExisted {
            get {
                return ResourceManager.GetString("ScriptIsNotExisted", resourceCulture);
            }
        }
        
        internal static string DoingDeleteScript {
            get {
                return ResourceManager.GetString("DoingDeleteScript", resourceCulture);
            }
        }
        
        internal static string DeleteScriptOK {
            get {
                return ResourceManager.GetString("DeleteScriptOK", resourceCulture);
            }
        }
        
        internal static string SetTimer {
            get {
                return ResourceManager.GetString("SetTimer", resourceCulture);
            }
        }
        
        internal static string SetContentPowerOn {
            get {
                return ResourceManager.GetString("SetContentPowerOn", resourceCulture);
            }
        }
        
        internal static string SetContentDevice {
            get {
                return ResourceManager.GetString("SetContentDevice", resourceCulture);
            }
        }
        
        internal static string Dayweek {
            get {
                return ResourceManager.GetString("Dayweek", resourceCulture);
            }
        }
        
        internal static string MaskAllDayweek {
            get {
                return ResourceManager.GetString("MaskAllDayweek", resourceCulture);
            }
        }
        
        internal static string ClearAllDayweek {
            get {
                return ResourceManager.GetString("ClearAllDayweek", resourceCulture);
            }
        }
        
        internal static string DeleteTimer {
            get {
                return ResourceManager.GetString("DeleteTimer", resourceCulture);
            }
        }
        
        internal static string SorryYouCanNotAddMore {
            get {
                return ResourceManager.GetString("SorryYouCanNotAddMore", resourceCulture);
            }
        }
        
        internal static string SorryThisScriptIsDeactivateCanNotControl {
            get {
                return ResourceManager.GetString("SorryThisScriptIsDeactivateCanNotControl", resourceCulture);
            }
        }
        
        internal static string TotalEvent {
            get {
                return ResourceManager.GetString("TotalEvent", resourceCulture);
            }
        }
        
        internal static string SupportPhone {
            get {
                return ResourceManager.GetString("SupportPhone", resourceCulture);
            }
        }
        
        internal static string PrimarySupportPhone {
            get {
                return ResourceManager.GetString("PrimarySupportPhone", resourceCulture);
            }
        }
        
        internal static string SecondarySupportPhone {
            get {
                return ResourceManager.GetString("SecondarySupportPhone", resourceCulture);
            }
        }
        
        internal static string SupportPhoneDescription {
            get {
                return ResourceManager.GetString("SupportPhoneDescription", resourceCulture);
            }
        }
        
        internal static string BuzzerSetup {
            get {
                return ResourceManager.GetString("BuzzerSetup", resourceCulture);
            }
        }
        
        internal static string BuzzerDescription {
            get {
                return ResourceManager.GetString("BuzzerDescription", resourceCulture);
            }
        }
        
        internal static string GMTSetup {
            get {
                return ResourceManager.GetString("GMTSetup", resourceCulture);
            }
        }
        
        internal static string GMTSetupDescription {
            get {
                return ResourceManager.GetString("GMTSetupDescription", resourceCulture);
            }
        }
        
        internal static string TemperatureThreadhold {
            get {
                return ResourceManager.GetString("TemperatureThreadhold", resourceCulture);
            }
        }
        
        internal static string TemperatureThreadholdDescription {
            get {
                return ResourceManager.GetString("TemperatureThreadholdDescription", resourceCulture);
            }
        }
        
        internal static string PleaseInputCorrectPhoneNumber {
            get {
                return ResourceManager.GetString("PleaseInputCorrectPhoneNumber", resourceCulture);
            }
        }
        
        internal static string TemperatureThreadHoldValueIsNotCorrect {
            get {
                return ResourceManager.GetString("TemperatureThreadHoldValueIsNotCorrect", resourceCulture);
            }
        }
        
        internal static string GMTValueIsNotCorrect {
            get {
                return ResourceManager.GetString("GMTValueIsNotCorrect", resourceCulture);
            }
        }
        
        internal static string DoingSyncToDevice {
            get {
                return ResourceManager.GetString("DoingSyncToDevice", resourceCulture);
            }
        }
        
        internal static string CanNotSyncToDevice {
            get {
                return ResourceManager.GetString("CanNotSyncToDevice", resourceCulture);
            }
        }
        
        internal static string IsSynced {
            get {
                return ResourceManager.GetString("IsSynced", resourceCulture);
            }
        }
        
        internal static string NotSynced {
            get {
                return ResourceManager.GetString("NotSynced", resourceCulture);
            }
        }
        
        internal static string SetupDeviceIsOK {
            get {
                return ResourceManager.GetString("SetupDeviceIsOK", resourceCulture);
            }
        }
        
        internal static string BackupSetupToCloud {
            get {
                return ResourceManager.GetString("BackupSetupToCloud", resourceCulture);
            }
        }
        
        internal static string DisplayLayer {
            get {
                return ResourceManager.GetString("DisplayLayer", resourceCulture);
            }
        }
        
        internal static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        internal static string Streetlight {
            get {
                return ResourceManager.GetString("Streetlight", resourceCulture);
            }
        }
        
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string MovePositionHelp {
            get {
                return ResourceManager.GetString("MovePositionHelp", resourceCulture);
            }
        }
        
        internal static string MovePosition {
            get {
                return ResourceManager.GetString("MovePosition", resourceCulture);
            }
        }
        
        internal static string UpdateNewDeviceLocation {
            get {
                return ResourceManager.GetString("UpdateNewDeviceLocation", resourceCulture);
            }
        }
        
        internal static string UpdateNewDeviceLocationFail {
            get {
                return ResourceManager.GetString("UpdateNewDeviceLocationFail", resourceCulture);
            }
        }
        
        internal static string FinishMoveLocation {
            get {
                return ResourceManager.GetString("FinishMoveLocation", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string ConfigServer {
            get {
                return ResourceManager.GetString("ConfigServer", resourceCulture);
            }
        }
        
        internal static string ConfigServerHint {
            get {
                return ResourceManager.GetString("ConfigServerHint", resourceCulture);
            }
        }
        
        internal static string ConfigServerDescription {
            get {
                return ResourceManager.GetString("ConfigServerDescription", resourceCulture);
            }
        }
        
        internal static string DoingRestoreDefaultConfig {
            get {
                return ResourceManager.GetString("DoingRestoreDefaultConfig", resourceCulture);
            }
        }
        
        internal static string RestoreConfigOK {
            get {
                return ResourceManager.GetString("RestoreConfigOK", resourceCulture);
            }
        }
        
        internal static string RestoreConfigFail {
            get {
                return ResourceManager.GetString("RestoreConfigFail", resourceCulture);
            }
        }
        
        internal static string CopyRightS3 {
            get {
                return ResourceManager.GetString("CopyRightS3", resourceCulture);
            }
        }
        
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Hotline {
            get {
                return ResourceManager.GetString("Hotline", resourceCulture);
            }
        }
        
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        internal static string SorryCantNotFoundInfo {
            get {
                return ResourceManager.GetString("SorryCantNotFoundInfo", resourceCulture);
            }
        }
        
        internal static string ConfigServerOK {
            get {
                return ResourceManager.GetString("ConfigServerOK", resourceCulture);
            }
        }
        
        internal static string DoingConfigServer {
            get {
                return ResourceManager.GetString("DoingConfigServer", resourceCulture);
            }
        }
        
        internal static string TypeOfControlMask {
            get {
                return ResourceManager.GetString("TypeOfControlMask", resourceCulture);
            }
        }
        
        internal static string MotionSensor {
            get {
                return ResourceManager.GetString("MotionSensor", resourceCulture);
            }
        }
        
        internal static string MotionSensorDescription {
            get {
                return ResourceManager.GetString("MotionSensorDescription", resourceCulture);
            }
        }
        
        internal static string ControlVirtualDescription {
            get {
                return ResourceManager.GetString("ControlVirtualDescription", resourceCulture);
            }
        }
        
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string ChangeUsernameAndPass {
            get {
                return ResourceManager.GetString("ChangeUsernameAndPass", resourceCulture);
            }
        }
        
        internal static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        internal static string SetDefaultLocation {
            get {
                return ResourceManager.GetString("SetDefaultLocation", resourceCulture);
            }
        }
        
        internal static string HelpAndGuideline {
            get {
                return ResourceManager.GetString("HelpAndGuideline", resourceCulture);
            }
        }
        
        internal static string ApplicationGuideline {
            get {
                return ResourceManager.GetString("ApplicationGuideline", resourceCulture);
            }
        }
        
        internal static string GatewayGuideline {
            get {
                return ResourceManager.GetString("GatewayGuideline", resourceCulture);
            }
        }
        
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        internal static string NewPasswordAndConfirmNewPasswordIsNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordAndConfirmNewPasswordIsNotMatch", resourceCulture);
            }
        }
        
        internal static string CurrentPasswordIsWrong {
            get {
                return ResourceManager.GetString("CurrentPasswordIsWrong", resourceCulture);
            }
        }
        
        internal static string UsernameIsExistedPleaseSelectAnother {
            get {
                return ResourceManager.GetString("UsernameIsExistedPleaseSelectAnother", resourceCulture);
            }
        }
        
        internal static string ChangeUsernameAndPassWarning {
            get {
                return ResourceManager.GetString("ChangeUsernameAndPassWarning", resourceCulture);
            }
        }
        
        internal static string PleaseInputUserName {
            get {
                return ResourceManager.GetString("PleaseInputUserName", resourceCulture);
            }
        }
        
        internal static string DoNotInputUsernameHasSpecialCharacter {
            get {
                return ResourceManager.GetString("DoNotInputUsernameHasSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string PleaseInputOldPassword {
            get {
                return ResourceManager.GetString("PleaseInputOldPassword", resourceCulture);
            }
        }
        
        internal static string DoNotInputOldPasswordHasSpecialCharacter {
            get {
                return ResourceManager.GetString("DoNotInputOldPasswordHasSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string PleaseInputNewPassword {
            get {
                return ResourceManager.GetString("PleaseInputNewPassword", resourceCulture);
            }
        }
        
        internal static string DoNotInputNewPasswordHasSpecialCharacter {
            get {
                return ResourceManager.GetString("DoNotInputNewPasswordHasSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string PleaseInputConfirmNewPassword {
            get {
                return ResourceManager.GetString("PleaseInputConfirmNewPassword", resourceCulture);
            }
        }
        
        internal static string DoNotInputConfirmNewPasswordHasSpecialCharacter {
            get {
                return ResourceManager.GetString("DoNotInputConfirmNewPasswordHasSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string DoingChangeUserNameAndPassword {
            get {
                return ResourceManager.GetString("DoingChangeUserNameAndPassword", resourceCulture);
            }
        }
        
        internal static string UpdateUserNameAndPasswordIsDoneSignout {
            get {
                return ResourceManager.GetString("UpdateUserNameAndPasswordIsDoneSignout", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string UpdateUserInfoIsOK {
            get {
                return ResourceManager.GetString("UpdateUserInfoIsOK", resourceCulture);
            }
        }
        
        internal static string PleaseInputDisplayName {
            get {
                return ResourceManager.GetString("PleaseInputDisplayName", resourceCulture);
            }
        }
        
        internal static string DoNotInputDisplayNameHasSpecialCharacter {
            get {
                return ResourceManager.GetString("DoNotInputDisplayNameHasSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string SavingScriptTimer {
            get {
                return ResourceManager.GetString("SavingScriptTimer", resourceCulture);
            }
        }
        
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        internal static string UpdateUserInfoWarning {
            get {
                return ResourceManager.GetString("UpdateUserInfoWarning", resourceCulture);
            }
        }
        
        internal static string UpdateUserLocationOK {
            get {
                return ResourceManager.GetString("UpdateUserLocationOK", resourceCulture);
            }
        }
        
        internal static string CameraQRNotSupport {
            get {
                return ResourceManager.GetString("CameraQRNotSupport", resourceCulture);
            }
        }
        
        internal static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        internal static string CameraQRNotSupportPleaseSetPermission {
            get {
                return ResourceManager.GetString("CameraQRNotSupportPleaseSetPermission", resourceCulture);
            }
        }
        
        internal static string WaterRefinneTitle {
            get {
                return ResourceManager.GetString("WaterRefinneTitle", resourceCulture);
            }
        }
        
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        internal static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        internal static string Litre {
            get {
                return ResourceManager.GetString("Litre", resourceCulture);
            }
        }
        
        internal static string NoDevicePleaseAddNew {
            get {
                return ResourceManager.GetString("NoDevicePleaseAddNew", resourceCulture);
            }
        }
        
        internal static string NoDevicePleaseAddNewDescription {
            get {
                return ResourceManager.GetString("NoDevicePleaseAddNewDescription", resourceCulture);
            }
        }
        
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        internal static string SetValueAndControl {
            get {
                return ResourceManager.GetString("SetValueAndControl", resourceCulture);
            }
        }
        
        internal static string SoldInfoSession {
            get {
                return ResourceManager.GetString("SoldInfoSession", resourceCulture);
            }
        }
        
        internal static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        internal static string SoldEvent {
            get {
                return ResourceManager.GetString("SoldEvent", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        internal static string PleaseSelectLitreOrMoneyToSold {
            get {
                return ResourceManager.GetString("PleaseSelectLitreOrMoneyToSold", resourceCulture);
            }
        }
        
        internal static string YouSelect {
            get {
                return ResourceManager.GetString("YouSelect", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        internal static string TotalOrders {
            get {
                return ResourceManager.GetString("TotalOrders", resourceCulture);
            }
        }
    }
}
